jwt:
  secret-key: ${JWT_SECRET:secret}
  access_token_life: ${JWT_EXPIRED:20}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: bankcards-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/db.changelog-master.yaml

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    resolve-schema-properties: true
  swagger-ui:
    url: /openapi.yaml
    path: /index.html
openapi:
  url: ${OPENAPI_URL}